spring.application.name=spring-ai-demo
spring.ai.deepseek.api-key=${DEEP_SEEK_KEY}
#????????
spring.ai.deepseek.chat.options.model=deepseek-chat
#spring.ai.deepseek.base-url=https://cloud.siliconflow.cn

#ali??
spring.ai.dashscope.api-key=${BAI_LIAN_KEY}
spring.ai.dashscope.chat.options.model=qwen-plus